### ISSUE TITLE
Bug: some clicking issues during animations

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [dmytrodanylyk/android-morphing-button#1]
1. it allows you to tap during animation, so double tapping actually start and stop the animation back to the original state, or worse: it goes to the next state, and doesn't do anything on the next tap you perform (as it thinks it's on the correct state).
2. when the button has rounded corners during animation, and you tap on it, it shows rectangle selection.

I think you can avoid both those issues by dis-allowing the user from tapping the button during animation play.

**Comment by sandeshlasnapure** [comment]
kjn

**Comment by redwerk** [comment]
Hi,

Here is PR for this issue.

**Comment by AndroidDeveloperLB** [comment]
@redwerk I don't understand.

**Comment by redwerk** [comment]
@AndroidDeveloperLB 
This is a PR for lib author, that fixes this issue.

**Comment by kiaanpillay** [comment]
Any update?

**Comment by JuanEsporrin** [comment]
My workaround for the clicking during the animation was to make the button unclickable for the animation time, and setting it back to clickable when the animation was over.

**Comment by hannesa2** [comment]
Issue seems to be linked to pull request
<img width="487" alt="image" src="https://user-images.githubusercontent.com/3314607/136148636-a151d4fe-1282-45b8-8852-9bf955781f25.png">
