### ISSUE TITLE
Gradle Sync Problem

### ISSUE THREAD

**Issue by JAICHANGPARK** [dmytrodanylyk/android-morphing-button#17]
**Now, I have some problem import master file.**

Error:(10, 0) Unable to find method 'org.gradle.api.internal.project.ProjectInternal.getPluginManager()Lorg/gradle/api/internal/plugins/PluginManagerInternal;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by polyak01** [comment]
the same problem

**Comment by hannesa2** [comment]
Please use [new version](url) and follow this howto https://github.com/dmytrodanylyk/android-morphing-button#integration or here https://jitpack.io/#dmytrodanylyk/android-morphing-button
