### ISSUE TITLE
unable to sync

### ISSUE THREAD

**Issue by xellDart** [dmytrodanylyk/android-morphing-button#22]
i cant sync this lib with gradle

**Comment by furkanozbay** [comment]
me too

**Comment by crazytaxii** [comment]
me too

**Comment by hamed1991** [comment]
me too

**Comment by crazytaxii** [comment]
I found it caused by my network then.

___________________

Regards
HF
TEL: 18800541190
China Wuxi

**Comment by hamed1991** [comment]
Unfortunately I have that problem yet with this error:
Failed to resolve: com.github.user:Repo:Tag
Error:(39,13)

**Comment by hamed1991** [comment]
And 
Failed to resolve: com.github.dmytrodanylyk:android-morphing-button:98a4986e56
Error:(45,10)

**Comment by pankajmindfreak** [comment]
@hamed1991 any solution to the Failed to resolve: com.github.dmytrodanylyk:android-morphing-button:98a4986e56
Error:(45,10)

**Comment by peiweijuhe** [comment]
same here, Failed to resolve: com.github.dmytrodanylyk:android-morphing-button:98a4986e56

**Comment by hannesa2** [comment]
Please use [new version](url) and follow this howto https://github.com/dmytrodanylyk/android-morphing-button#integration or here https://jitpack.io/#dmytrodanylyk/android-morphing-button
