### ISSUE TITLE
Objects allocations in onDraw()

### ISSUE THREAD

**Issue by sergeyfitis** [dmytrodanylyk/android-morphing-button#3]
You have objects allocations in onDraw() method which in class LinearProgressButton.

**Comment by dmytrodanylyk** [comment]
@sergeyfitis can u point to line of code?

**Comment by sergeyfitis** [comment]
@dmytrodanylyk https://sc-cdn.scaleengine.net/i/671a873bd2c15984ee1d70936fa37fcb.png

**Comment by sergeyfitis** [comment]
Забираю свою претензію, не побачив перевірки на нул )

**Comment by sergeyfitis** [comment]
@dmytrodanylyk Доречі, це апдейт старої бібліотеки чи написано з нуля?

**Comment by dmytrodanylyk** [comment]
Написано з нуля на заміну старої бібліотеки. Стару було важко додавати функціонал.

**Comment by sergeyfitis** [comment]
@dmytrodanylyk Дякую, чекаю твого виступу на GDG Lviv
