### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ekslight** [dmytrodanylyk/android-morphing-button#6]
Hello!
Why is the 6-th line code may call the exception when try to run app? 
And the 7-th line is OK.
The same exception occur, when i try to adress to any resourses like String or Color.

 1   MorphingButton.Params sim_m = MorphingButton.Params.create()
 2          .duration(500)
 3          .cornerRadius(3)
 4          .width(135)
 5          .height(56)
 6          .color(color(R.color.Sim))
 7          .colorPressed(Color.parseColor("#00796B"));

I'm sorry, maybe i don't know something...
Thanks you for your MorphingButton!

**Comment by dmytrodanylyk** [comment]
@ekslight I assume your context is null.

**Comment by ekslight** [comment]
@dmytrodanylyk Sorry, i dont understand where i need insert context wrapper.
In the metods, that use getResources?

**Comment by dmytrodanylyk** [comment]
@ekslight so it means this is not related to library. If `getApplicationContent` return null it means you are doing something weird :)

**Comment by ekslight** [comment]
@dmytrodanylyk ok, thank you, will look for the problem.
